apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    kubernetes.io/part-of: vote-app
    kubernetes.io/app: db
    kubernetes.io/component: db
    kubernetes.io/manual: "true"
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    kubernetes.io/part-of: vote-app
    kubernetes.io/app: db
    kubernetes.io/component: db
